### ISSUE TITLE
Can't Make Any Users, Including Superuser without Pro

### ISSUE THREAD

**Issue by grovberg** [Afan417/blogo-starter-kit#3]
Making a super-user during installation with Blogo resulted in a "Statamic Pro is required." error. Trying to manually create a user with _php please make:user_ gave the same result. Is this expected behavior?

**Comment by cdillon** [comment]
You have to delete `users\john@doe.com.yaml` first.

**Comment by afan417** [comment]
> You have to delete `users\john@doe.com.yaml` first.

This is the answer, if you want to create a new super-user without needing Statamic Pro.

You already have a super-user when you install Blogo, I will update the documentation for this, cheers.

**Comment by grovberg** [comment]
Makes sense. Thanks for the response.

**Comment by kopachlager** [comment]
I'm still having the issue with this, even when manually deleting the user file although after deleting deployment failed. Make user command does not work. Any other suggestions?
