### ISSUE TITLE
Starter kit config [starter-kit.yaml] does not exist.

### ISSUE THREAD

**Issue by joenyambura** [Afan417/blogo-starter-kit#5]
I am getting the following error when I try to install this startertkit

![Screenshot from 2024-01-24 19-47-29](https://github.com/Afan417/blogo-starter-kit/assets/4881768/d5296a7a-2c3f-4373-9db5-c04b44f22c32)

Kindly help

**Comment by afan417** [comment]
Hello there @joenyambura,

Have you figured this out yet? Since this issue is kinda old, let me know, thanks!

**Comment by afan417** [comment]
Closing this, create a new issue if it still occurs.
